# Generated by Django 5.1.7 on 2025-03-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="average_transaction_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
