# Generated by Django 5.1.7 on 2025-03-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_userprofile_average_transaction_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="allowed_locations",
            field=models.TextField(default=""),
        ),
    ]
