# Generated by Django 5.1.7 on 2025-03-31 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_fraudrule"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
